// Sidebar
export const SIDEBAR_VISIBILITY_TOGGLE = "SIDEBAR_VISIBILITY_TOGGLE";
export const SIDEBAR_VISIBILITY_SHOW = "SIDEBAR_VISIBILITY_SHOW";
export const SIDEBAR_VISIBILITY_HIDE = "SIDEBAR_VISIBILITY_HIDE";
export const SIDEBAR_STICKY_TOGGLE = "SIDEBAR_STICKY_TOGGLE";
export const SIDEBAR_STICKY_ENABLE = "SIDEBAR_STICKY_ENABLE";
export const SIDEBAR_STICKY_DISABLE = "SIDEBAR_STICKY_DISABLE";

// Layout
export const LAYOUT_BOXED_TOGGLE = "LAYOUT_BOXED_TOGGLE";
export const LAYOUT_BOXED_ENABLE = "LAYOUT_BOXED_ENABLE";
export const LAYOUT_BOXED_DISABLE = "LAYOUT_BOXED_DISABLE";

// Theme
export const THEME_TOGGLE = "THEME_TOGGLE";

// token & login
export const TOKEN_INFO = "TOKEN_INFO";
export const USER_LOGIN_INFO = "USER_LOGIN_INFO";
export const REMEMBER_ME_INFO = "REMEMBER_ME_INFO";

// document
export const GET_LIST_DOCUMENT = "GET_LIST_DOCUMENT";

// subject
export const GET_LIST_SUBJECT = "GET_LIST_SUBJECT";

// course
export const GET_LIST_COURSE = "GET_LIST_COURSE";

// class
export const GET_LIST_CLASS = "GET_LIST_CLASS";
export const GET_LIST_CLASS_ACTIVE = "GET_LIST_CLASS_ACTIVE";

// mentor
export const GET_LIST_MENTOR = "GET_LIST_MENTOR";

// mentee
export const GET_LIST_MENTEE = "GET_LIST_MENTEE";

// change attendance
export const ATTENDANCE_FINISHED_CHANGE_DATE = "ATTENDANCE_FINISHED_CHANGE_DATE";
export const ATTENDANCE_FINISHED_CHANGE_TYPE_MENTEE = "ATTENDANCE_FINISHED_CHANGE_TYPE_MENTEE";
export const ATTENDANCE_UNFINISHED_CHANGE_DATE_AND_INIT_MENTEE_ATTENDANCE = "ATTENDANCE_UNFINISHED_CHANGE_DATE_AND_INIT_MENTEE_ATTENDANCE";
export const ATTENDANCE_UNFINISHED_CHANGE_DATE = "ATTENDANCE_UNFINISHED_CHANGE_DATE";
export const ATTENDANCE_UNFINISHED_CHANGE_TYPE_MENTEE = "ATTENDANCE_UNFINISHED_CHANGE_TYPE_MENTEE";
export const ATTENDANCE_RESET = "ATTENDANCE_RESET";